// src/components/fragments/Thanks.svelte
<script>
  import { fly } from 'svelte/transition'
  import { quintIn, quintOut } from 'svelte/easing'
  import { createEventDispatcher } from 'svelte'

  const dispatch = createEventDispatcher()
  export let text, success

  const exit = (e = true) => {
    e && dispatch('exit')
  }

  let r
  $: l = -1 * r
  const divOp = { duration: 500, easing: quintIn }
</script>

<svelte:window
  on:keypress="{e => exit(e.key === 'Enter')}"
  bind:innerWidth="{r}"
></svelte:window>

<div
  in:fly="{{...divOp, x: r}}"
  out:fly="{{...divOp, x: l}}"
  on:click="{exit}"
  on:introstart="{()=> console.log(r, l)}"
  on:introend="{()=> console.log(r, l)}"
  on:outrostart="{()=> console.log(r, l)}"
>
  <p class:success class:fail="{!success}">
    {text}
  </p>
</div>

<style>
  div {
    position: fixed;
    bottom: 35%;
    top: 35%;
    left: 0;
    right: 0;
    background-color: rgba(255, 255, 255, 0.7);
    cursor: pointer;
  }
  p {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -55%);
    padding: 2rem 3rem;
    font-size: 1.6rem;
    white-space: pre;
    text-align: center;
    line-height: 1.6;
  }
  p:before {
    display: inline-block;
    width: 3rem;
    position: relative;
  }
  .success:before {
    content: url('/svg/checkbox.svg');
    left: -0.4rem;
    bottom: -0.6rem;
  }
  .fail:before {
    content: url('/svg/nope.svg');
    left: -0.5rem;
    bottom: -3rem;
  }
  @media (max-width: 580px) {
    p {
      font-size: 1.2rem;
    }
    .fail:before {
      left: -0.1rem;
    }
  }
</style>

// src/components/fragments/Thanks.vue
<template>
  <div class="white-out">
    <div class="thanks">
      <h1>{{ $t('thanks.caption') }}</h1>
      <p>{{ $t('thanks.message') }}</p>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.white-out {
  width: 100%;
  height: 100%;
  background-color: rgba(255, 255, 255, 0.75);
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: 100;
  display: flex;
  align-items: center;
  justify-content: center;
}
.thanks {
  height: 15rem;
  width: 30rem;
  padding: 2rem 3rem;
  text-align: center;
  background-color: $white-p;
  border-radius: 1rem;

  & h1 {
    margin-top: 1rem;
    margin-bottom: 2rem;
    font-size: 2.5rem;
  }

  & p {
    font-size: 2rem;
  }
}
</style>
